---
- hosts: localhost

  

  tasks:

    - name: Logon to CyberArk Vault using PAS Web Services SDK
      cyberark_authentication:
        api_base_url: "fmcunixssh.fmcna.com"
        validate_certs: no
        username: "z00663295@CSDmanager@hal-csdd-q04.dc.fmcna.com"
        password: "Safety@swim1195"


    - name: Debug message
      debug:
        var: cyberark_session


    - name: Logoff from CyberArk Vault
      cyberark_authentication:
        state: absent
        cyberark_session: "{{ cyberark_session }}"

    - name: Debug message
      debug: var=cyberark_session
